<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\Pricefile\AbstractModels;

use Illuminate\Database\Eloquent\Model;

/**
* Class AbstractBBInformation
* @package App\Models\Pricefile\AbstractModels
*
* @property bigInteger $id
* @property bigInteger $id_api
* @property string $sku
* @property string $name
* @property text $description
* @property string $url
* @property \Carbon\Carbon $dateUpdDescription
* @property text $shortDescription
* @property text $descriptionRetailer
* @property text $translation
* @property text $metaKeywords
* @property text $manufacturer
* @property \Carbon\Carbon $created_at
* @property \Carbon\Carbon $updated_at
*/ 
abstract class AbstractBBInformation extends Model
{
    /**  
     * The table associated with the model.
     * 
     * @var string
     */
    protected $table = 'bbinformation';
    
    /**  
     * Customize column name for created_at timestamp
     * 
     * @var string
     */
    protected $CREATED_AT = 'created_at';
    
    /**  
     * Customize column name for updated_at timestamp
     * 
     * @var string
     */
    protected $UPDATED_AT = 'updated_at';
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'id_api' => 'integer',
        'sku' => 'string',
        'name' => 'string',
        'description' => 'string',
        'url' => 'string',
        'dateUpdDescription' => 'datetime',
        'shortDescription' => 'string',
        'descriptionRetailer' => 'string',
        'translation' => 'string',
        'metaKeywords' => 'string',
        'manufacturer' => 'string',
        'created_at' => 'datetime',
        'updated_at' => 'datetime'
    ];
    
    /**  
     * The attributes that are mass assignable.
     * 
     * @var array
     */
    protected $fillable = [
        'id_api',
        'sku',
        'name',
        'description',
        'url',
        'dateUpdDescription',
        'shortDescription',
        'descriptionRetailer',
        'translation',
        'metaKeywords',
        'manufacturer'
    ];
}
