<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\Pricefile\AbstractModels;

use Illuminate\Database\Eloquent\Model;

/**
* Class AbstractBBStock
* @package App\Models\Pricefile\AbstractModels
*
* @property bigInteger $id
* @property bigInteger $id_api
* @property string $sku
* @property bigInteger $stock_quantity
* @property bigInteger $stock_min_handling_days
* @property bigInteger $stock_max_handling_days
* @property bigInteger $stock_warehouse
* @property \Carbon\Carbon $updated_at
* @property \Carbon\Carbon $created_at
*/ 
abstract class AbstractBBStock extends Model
{
    /**  
     * The table associated with the model.
     * 
     * @var string
     */
    protected $table = 'bbstocks';
    
    /**  
     * Customize column name for created_at timestamp
     * 
     * @var string
     */
    protected $CREATED_AT = 'created_at';
    
    /**  
     * Customize column name for updated_at timestamp
     * 
     * @var string
     */
    protected $UPDATED_AT = 'updated_at';
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'id_api' => 'integer',
        'sku' => 'string',
        'stock_quantity' => 'integer',
        'stock_min_handling_days' => 'integer',
        'stock_max_handling_days' => 'integer',
        'stock_warehouse' => 'integer',
        'updated_at' => 'datetime',
        'created_at' => 'datetime'
    ];
    
    /**  
     * The attributes that are mass assignable.
     * 
     * @var array
     */
    protected $fillable = [
        'id_api',
        'sku',
        'stock_quantity',
        'stock_min_handling_days',
        'stock_max_handling_days',
        'stock_warehouse'
    ];
}
