<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\Pricefile\AbstractModels;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
* Class AbstractBBManufacturer
* @package App\Models\Pricefile\AbstractModels
*
* @property bigInteger $id
* @property bigInteger $id_api
* @property string $name
* @property string $url_image
* @property bigInteger $reference
* @property boolean $active
* @property \Carbon\Carbon $created_at
* @property \Carbon\Carbon $updated_at
* @property \Carbon\Carbon $deleted_at
*/ 
abstract class AbstractBBManufacturer extends Model
{
    use SoftDeletes;
    
    /**  
     * The table associated with the model.
     * 
     * @var string
     */
    protected $table = 'bbmanufacturer';
    
    /**  
     * The model's default values for attributes.
     * 
     * @var array
     */
    protected $attributes = ['active' => false];
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'id_api' => 'integer',
        'name' => 'string',
        'url_image' => 'string',
        'reference' => 'integer',
        'active' => 'boolean',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
        'deleted_at' => 'datetime'
    ];
    
    /**  
     * The attributes that are mass assignable.
     * 
     * @var array
     */
    protected $fillable = [
        'id_api',
        'name',
        'url_image',
        'reference',
        'active'
    ];
}
