<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\Pricefile\AbstractModels;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
* Class AbstractFiles
* @package App\Models\Pricefile\AbstractModels
*
* @property bigInteger $id
* @property string $name
* @property \Carbon\Carbon $file_timestamp
* @property bigInteger $size
* @property string $hash_md5
* @property string $hash_sha1
* @property boolean $api
* @property \Carbon\Carbon $start_at
* @property \Carbon\Carbon $done_at
* @property \Carbon\Carbon $created_at
* @property \Carbon\Carbon $updated_at
* @property \Carbon\Carbon $deleted_at
* @property \Illuminate\Database\Eloquent\Collection $despecs
*/ 
abstract class AbstractFiles extends Model
{
    use SoftDeletes;
    
    /**  
     * The model's default values for attributes.
     * 
     * @var array
     */
    protected $attributes = ['api' => False];
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'name' => 'string',
        'file_timestamp' => 'datetime',
        'size' => 'integer',
        'hash_md5' => 'string',
        'hash_sha1' => 'string',
        'api' => 'boolean',
        'start_at' => 'datetime',
        'done_at' => 'datetime',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
        'deleted_at' => 'datetime'
    ];
    
    /**  
     * The attributes that are mass assignable.
     * 
     * @var array
     */
    protected $fillable = [
        'name',
        'file_timestamp',
        'size',
        'hash_md5',
        'hash_sha1',
        'api',
        'start_at',
        'done_at'
    ];
    
    public function despecs()
    {
        return $this->hasMany('\App\Models\Pricefile\Despec', 'file_id', 'id');
    }
}
