<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\Pricefile\AbstractModels;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
* Class AbstractBBImage
* @package App\Models\Pricefile\AbstractModels
*
* @property bigInteger $id
* @property bigInteger $id_api
* @property bigInteger $image_id
* @property string $url
* @property boolean $cover
* @property boolean $logo
* @property boolean $whiteBackground
* @property string $file
* @property \Carbon\Carbon $created_at
* @property \Carbon\Carbon $updated_at
* @property \Carbon\Carbon $deleted_at
*/ 
abstract class AbstractBBImage extends Model
{
    use SoftDeletes;
    
    /**  
     * The table associated with the model.
     * 
     * @var string
     */
    protected $table = 'bbimages';
    
    /**  
     * Customize column name for created_at timestamp
     * 
     * @var string
     */
    protected $CREATED_AT = 'created_at';
    
    /**  
     * Customize column name for updated_at timestamp
     * 
     * @var string
     */
    protected $UPDATED_AT = 'updated_at';
    
    /**  
     * The model's default values for attributes.
     * 
     * @var array
     */
    protected $attributes = [
        'cover' => false,
        'logo' => false,
        'whiteBackground' => false
    ];
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'id_api' => 'integer',
        'image_id' => 'integer',
        'url' => 'string',
        'cover' => 'boolean',
        'logo' => 'boolean',
        'whiteBackground' => 'boolean',
        'file' => 'string',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
        'deleted_at' => 'datetime'
    ];
    
    /**  
     * The attributes that are mass assignable.
     * 
     * @var array
     */
    protected $fillable = [
        'id_api',
        'image_id',
        'url',
        'cover',
        'logo',
        'whiteBackground',
        'file'
    ];
}
