<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\Pricefile\AbstractModels;

use Illuminate\Database\Eloquent\Model;

/**
* Class AbstractBBProductsTaxonomies
* @package App\Models\Pricefile\AbstractModels
*
* @property bigInteger $id
* @property bigInteger $taxonomy
* @property bigInteger $product
*/ 
abstract class AbstractBBProductsTaxonomies extends Model
{
    /**  
     * The table associated with the model.
     * 
     * @var string
     */
    protected $table = 'bbproducts_taxonomies';
    
    /**  
     * Do not automatically manage timestamps by Eloquent
     * 
     * @var bool
     */
    public $timestamps = false;
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'taxonomy' => 'integer',
        'product' => 'integer'
    ];
    
    /**  
     * The attributes that are mass assignable.
     * 
     * @var array
     */
    protected $fillable = [
        'taxonomy',
        'product'
    ];
}
