<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\Pricefile\AbstractModels;

use Illuminate\Database\Eloquent\Model;

/**
* Class AbstractBBProduct
* @package App\Models\Pricefile\AbstractModels
*
* @property bigInteger $id
* @property bigInteger $id_api
* @property string $sku
* @property string $manufacturer
* @property string $ean13
* @property decimal $weight
* @property decimal $height
* @property decimal $width
* @property decimal $depth
* @property \Carbon\Carbon $dateUpd
* @property bigInteger $category
* @property \Carbon\Carbon $dateUpdDescription
* @property \Carbon\Carbon $dateUpdImages
* @property \Carbon\Carbon $dateUpdStock
* @property decimal $wholesalePrice
* @property decimal $retailPrice
* @property \Carbon\Carbon $dateAdd
* @property string $video
* @property boolean $active
* @property boolean $attributes
* @property boolean $categories
* @property boolean $images
* @property integer $taxRate
* @property integer $taxId
* @property decimal $inShopsPrice
* @property string $condition
* @property string $logisticClass
* @property boolean $tags
* @property string $intrastat
*/ 
abstract class AbstractBBProduct extends Model
{
    /**  
     * The table associated with the model.
     * 
     * @var string
     */
    protected $table = 'bbproducts';
    
    /**  
     * Do not automatically manage timestamps by Eloquent
     * 
     * @var bool
     */
    public $timestamps = false;
    
    /**  
     * Customize column name for created_at timestamp
     * 
     * @var string
     */
    protected $CREATED_AT = 'created_at';
    
    /**  
     * Customize column name for updated_at timestamp
     * 
     * @var string
     */
    protected $UPDATED_AT = 'updated_at';
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'id_api' => 'integer',
        'sku' => 'string',
        'manufacturer' => 'string',
        'ean13' => 'string',
        'weight' => 'decimal:2',
        'height' => 'decimal:2',
        'width' => 'decimal:2',
        'depth' => 'decimal:2',
        'dateUpd' => 'datetime',
        'category' => 'integer',
        'dateUpdDescription' => 'datetime',
        'dateUpdImages' => 'datetime',
        'dateUpdStock' => 'datetime',
        'wholesalePrice' => 'decimal:2',
        'retailPrice' => 'decimal:2',
        'dateAdd' => 'datetime',
        'video' => 'string',
        'active' => 'boolean',
        'attributes' => 'boolean',
        'categories' => 'boolean',
        'images' => 'boolean',
        'taxRate' => 'integer',
        'taxId' => 'integer',
        'inShopsPrice' => 'decimal:2',
        'condition' => 'string',
        'logisticClass' => 'string',
        'tags' => 'boolean',
        'intrastat' => 'string'
    ];
    
    /**  
     * The attributes that are mass assignable.
     * 
     * @var array
     */
    protected $fillable = [
        'id_api',
        'sku',
        'manufacturer',
        'ean13',
        'weight',
        'height',
        'width',
        'depth',
        'dateUpd',
        'category',
        'dateUpdDescription',
        'dateUpdImages',
        'dateUpdStock',
        'wholesalePrice',
        'retailPrice',
        'dateAdd',
        'video',
        'active',
        'attributes',
        'categories',
        'images',
        'taxRate',
        'inShopsPrice',
        'condition',
        'logisticClass',
        'tags',
        'intrastat'
    ];
}
