<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\Pricefile\AbstractModels;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
* Class AbstractDespec
* @package App\Models\Pricefile\AbstractModels
*
* @property bigInteger $id
* @property bigInteger $file_id
* @property string $item_id
* @property integer $qty
* @property string $item_oem
* @property string $item_ean
* @property string $item
* @property string $item_txt
* @property text $item_web_desc
* @property string $unit
* @property integer $stock_actual
* @property \Carbon\Carbon $expected_date
* @property bigInteger $price
* @property bigInteger $price_tax_and_fees
* @property string $currency
* @property bigInteger $vat_tax
* @property string $item_type
* @property string $brand
* @property bigInteger $weight
* @property bigInteger $volume
* @property bigInteger $height
* @property bigInteger $width
* @property bigInteger $depth
* @property bigInteger $add_fees_tax
* @property string $cust_item_id
* @property string $create_date_time
* @property string $stat_code
* @property string $orig_country
* @property bigInteger $min_q
* @property integer $multiples
* @property integer $colli
* @property string $brand_txt
* @property string $item_type_txt
* @property string $non_stock_item_txt
* @property string $bid_id
* @property \Carbon\Carbon $created_at
* @property \Carbon\Carbon $updated_at
* @property \Carbon\Carbon $deleted_at
* @property \App\Models\Pricefile\Files|null $files
*/ 
abstract class AbstractDespec extends Model
{
    use SoftDeletes;
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'file_id' => 'integer',
        'item_id' => 'string',
        'qty' => 'integer',
        'item_oem' => 'string',
        'item_ean' => 'string',
        'item' => 'string',
        'item_txt' => 'string',
        'item_web_desc' => 'string',
        'unit' => 'string',
        'stock_actual' => 'integer',
        'expected_date' => 'datetime:Y-m-d',
        'price' => 'integer',
        'price_tax_and_fees' => 'integer',
        'currency' => 'string',
        'vat_tax' => 'integer',
        'item_type' => 'string',
        'brand' => 'string',
        'weight' => 'integer',
        'volume' => 'integer',
        'height' => 'integer',
        'width' => 'integer',
        'depth' => 'integer',
        'add_fees_tax' => 'integer',
        'cust_item_id' => 'string',
        'create_date_time' => 'string',
        'stat_code' => 'string',
        'orig_country' => 'string',
        'min_q' => 'integer',
        'multiples' => 'integer',
        'colli' => 'integer',
        'brand_txt' => 'string',
        'item_type_txt' => 'string',
        'non_stock_item_txt' => 'string',
        'bid_id' => 'string',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
        'deleted_at' => 'datetime'
    ];
    
    /**  
     * The attributes that are mass assignable.
     * 
     * @var array
     */
    protected $fillable = [
        'file_id',
        'item_id',
        'qty',
        'item_oem',
        'item_ean',
        'item',
        'item_txt',
        'item_web_desc',
        'unit',
        'stock_actual',
        'expected_date',
        'price',
        'price_tax_and_fees',
        'currency',
        'vat_tax',
        'item_type',
        'brand',
        'weight',
        'volume',
        'height',
        'width',
        'depth',
        'add_fees_tax',
        'cust_item_id',
        'create_date_time',
        'stat_code',
        'orig_country',
        'min_q',
        'multiples',
        'colli',
        'brand_txt',
        'item_type_txt',
        'non_stock_item_txt',
        'bid_id'
    ];
    
    public function files()
    {
        return $this->belongsTo('\App\Models\Pricefile\Files', 'file_id', 'id');
    }
}
