<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\Pricefile\AbstractModels;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
* Class AbstractBBCategory
* @package App\Models\Pricefile\AbstractModels
*
* @property bigInteger $id
* @property bigInteger $id_api
* @property bigInteger $parent_id
* @property string $name
* @property string $urls
* @property string $image_urls
* @property \Carbon\Carbon $date_add
* @property \Carbon\Carbon $date_upd
* @property \Carbon\Carbon $created_at
* @property \Carbon\Carbon $updated_at
* @property \Carbon\Carbon $deleted_at
*/ 
abstract class AbstractBBCategory extends Model
{
    use SoftDeletes;
    
    /**  
     * The table associated with the model.
     * 
     * @var string
     */
    protected $table = 'bbcategories';
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'id_api' => 'integer',
        'parent_id' => 'integer',
        'name' => 'string',
        'urls' => 'string',
        'image_urls' => 'string',
        'date_add' => 'datetime',
        'date_upd' => 'datetime',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
        'deleted_at' => 'datetime'
    ];
    
    /**  
     * The attributes that are mass assignable.
     * 
     * @var array
     */
    protected $fillable = [
        'id_api',
        'parent_id',
        'name',
        'urls',
        'image_urls',
        'date_add',
        'date_upd'
    ];
}
