<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\Product\AbstractModels;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
* Class AbstractPurchasePrice
* @package App\Models\Product\AbstractModels
*
* @property bigInteger $id
* @property bigInteger $product_id
* @property bigInteger $supplier_id
* @property string $article_number
* @property integer $stock
* @property boolean $stock_out
* @property \Carbon\Carbon $stock_incoming
* @property boolean $stock_discontinued
* @property decimal $price
* @property decimal $price_retail
* @property decimal $price_in_shops
* @property string $currency
* @property \Carbon\Carbon $valid_to
* @property \Carbon\Carbon $valid_from
* @property boolean $campaign
* @property boolean $realisation
* @property string $intrastat
* @property \Carbon\Carbon $created_at
* @property \Carbon\Carbon $updated_at
* @property \Carbon\Carbon $deleted_at
* @property \App\Models\Product\Product $product
* @property \App\Models\Product\Supplier $supplier
*/ 
abstract class AbstractPurchasePrice extends Model
{
    use SoftDeletes;
    
    /**  
     * The table associated with the model.
     * 
     * @var string
     */
    protected $table = 'purchase_price';
    
    /**  
     * Customize column name for created_at timestamp
     * 
     * @var string
     */
    protected $CREATED_AT = 'created_at';
    
    /**  
     * Customize column name for updated_at timestamp
     * 
     * @var string
     */
    protected $UPDATED_AT = 'updated_at';
    
    /**  
     * The model's default values for attributes.
     * 
     * @var array
     */
    protected $attributes = [
        'stock_discontinued' => False,
        'currency' => 'SEK',
        'campaign' => False,
        'realisation' => False
    ];
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'product_id' => 'integer',
        'supplier_id' => 'integer',
        'article_number' => 'string',
        'stock' => 'integer',
        'stock_out' => 'boolean',
        'stock_incoming' => 'datetime:Y-m-d',
        'stock_discontinued' => 'boolean',
        'price' => 'decimal:2',
        'price_retail' => 'decimal:2',
        'price_in_shops' => 'decimal:2',
        'currency' => 'string',
        'valid_to' => 'datetime',
        'valid_from' => 'datetime',
        'campaign' => 'boolean',
        'realisation' => 'boolean',
        'intrastat' => 'string',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
        'deleted_at' => 'datetime'
    ];
    
    /**  
     * The attributes that are mass assignable.
     * 
     * @var array
     */
    protected $fillable = [
        'product_id',
        'supplier_id',
        'article_number',
        'stock',
        'stock_out',
        'stock_incoming',
        'stock_discontinued',
        'price',
        'price_retail',
        'price_in_shops',
        'currency',
        'valid_to',
        'valid_from',
        'campaign',
        'realisation',
        'intrastat'
    ];
    
    public function product()
    {
        return $this->belongsTo('\App\Models\Product\Product', 'product_id', 'id');
    }
    
    public function supplier()
    {
        return $this->belongsTo('\App\Models\Product\Supplier', 'supplier_id', 'id');
    }
}
