<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\Partner\AbstractModels;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
* Class AbstractDiscountCode
* @package App\Models\Partner\AbstractModels
*
* @property bigInteger $id
* @property bigInteger $partner_id
* @property string $partner_name
* @property string $code
* @property \Carbon\Carbon $created_at
* @property \Carbon\Carbon $updated_at
* @property \Carbon\Carbon $deleted_at
* @property \App\Models\Partner\Partner|null $partner
* @property \Illuminate\Database\Eloquent\Collection $orderRows
*/ 
abstract class AbstractDiscountCode extends Model
{
    use SoftDeletes;
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'partner_id' => 'integer',
        'partner_name' => 'string',
        'code' => 'string',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
        'deleted_at' => 'datetime'
    ];
    
    public function partner()
    {
        return $this->belongsTo('\App\Models\Partner\Partner', 'partner_id', 'id');
    }
    
    public function orderRows()
    {
        return $this->hasMany('\App\Models\Order\OrderRow', 'discount_code_id', 'id');
    }
}
