<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\Partner\AbstractModels;

use Illuminate\Database\Eloquent\Model;

/**
* Class AbstractTransactions
* @package App\Models\Partner\AbstractModels
*
* @property bigInteger $id
* @property bigInteger $ledger_id
* @property bigInteger $order_row_id
* @property bigInteger $user_id
* @property bigInteger $amount
* @property \Carbon\Carbon $active_at
* @property string $description
* @property json $orders
* @property \Carbon\Carbon $created_at
* @property \Carbon\Carbon $updated_at
* @property \App\Models\Partner\Ledger $ledger
* @property \App\Models\User|null $user
* @property \App\Models\Order\OrderRow|null $orderRow
*/ 
abstract class AbstractTransactions extends Model
{
    /**  
     * The table associated with the model.
     * 
     * @var string
     */
    protected $table = 'transactions';
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'ledger_id' => 'integer',
        'order_row_id' => 'integer',
        'user_id' => 'integer',
        'amount' => 'integer',
        'active_at' => 'datetime',
        'description' => 'string',
        'orders' => 'array',
        'created_at' => 'datetime',
        'updated_at' => 'datetime'
    ];
    
    public function ledger()
    {
        return $this->belongsTo('\App\Models\Partner\Ledger', 'ledger_id', 'id');
    }
    
    public function user()
    {
        return $this->belongsTo('\App\Models\User', 'user_id', 'id');
    }
    
    public function orderRow()
    {
        return $this->belongsTo('\App\Models\Order\OrderRow', 'order_row_id', 'id');
    }
}
