<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\Cart\AbstractModels;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
* Class AbstractCartRow
* @package App\Models\Cart\AbstractModels
*
* @property bigInteger $id
* @property bigInteger $cart_id
* @property bigInteger $product_id
* @property integer $price_add
* @property \Carbon\Carbon $created_at
* @property \Carbon\Carbon $updated_at
* @property \Carbon\Carbon $deleted_at
* @property \App\Models\Cart\Cart $cart
* @property \App\Models\Product\Product|null $product
*/ 
abstract class AbstractCartRow extends Model
{
    use SoftDeletes;
    
    /**  
     * The table associated with the model.
     * 
     * @var string
     */
    protected $table = 'cart_rows';
    
    /**  
     * Customize column name for created_at timestamp
     * 
     * @var string
     */
    protected $CREATED_AT = 'created_at';
    
    /**  
     * Customize column name for updated_at timestamp
     * 
     * @var string
     */
    protected $UPDATED_AT = 'updated_at';
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'cart_id' => 'integer',
        'product_id' => 'integer',
        'price_add' => 'integer',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
        'deleted_at' => 'datetime'
    ];
    
    /**  
     * The attributes that are mass assignable.
     * 
     * @var array
     */
    protected $fillable = [
        'cart_id',
        'product_id',
        'price_add'
    ];
    
    public function cart()
    {
        return $this->belongsTo('\App\Models\Cart\Cart', 'cart_id', 'id');
    }
    
    public function product()
    {
        return $this->belongsTo('\App\Models\Product\Product', 'product_id', 'id');
    }
}
