<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\Order\AbstractModels;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
* Class AbstractParcels
* @package App\Models\Order\AbstractModels
*
* @property bigInteger $id
* @property enum $status
* @property text $identifier
* @property string $carrier
* @property \Carbon\Carbon $sent_at
* @property \Carbon\Carbon $delivered_at
* @property \Carbon\Carbon $created_at
* @property \Carbon\Carbon $updated_at
* @property \Carbon\Carbon $deleted_at
* @property \Illuminate\Database\Eloquent\Collection $orderRows
*/ 
abstract class AbstractParcels extends Model
{
    use SoftDeletes;
    
    /**  
     * The model's default values for attributes.
     * 
     * @var array
     */
    protected $attributes = ['status' => "ordered"];
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'status' => 'string',
        'identifier' => 'string',
        'carrier' => 'string',
        'sent_at' => 'datetime',
        'delivered_at' => 'datetime',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
        'deleted_at' => 'datetime'
    ];
    
    /**  
     * The attributes that are mass assignable.
     * 
     * @var array
     */
    protected $fillable = [
        'identifier',
        'carrier',
        'sent_at'
    ];
    
    public function orderRows()
    {
        return $this->hasMany('\App\Models\Order\OrderRow', 'parcels_id', 'id');
    }
}
