<?php
/* 
 * Migrations generated by: Skipper (http://www.skipper18.com)
 * Migration id: e5d0f335-9e01-4592-b7aa-3a5cae12117b-01
 * Migration local datetime: 2023-04-30 20:47:49.177812
 * Migration UTC datetime: 2023-04-30 18:47:49.177812
 */ 

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class SkipperMigrations01Cart2023043020474917 extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('cart_rows', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->bigInteger('cart_id');
            $table->bigInteger('product_id')->nullable(true)->unsigned();
            $table->integer('price_add')->nullable(true);
            $table->timestamp('created_at')->nullable(true);
            $table->timestamp('updated_at')->nullable(true);
            $table->timestamp('deleted_at')->nullable(true);
        });
        Schema::create('carts', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement();
            $table->bigInteger('user_id')->nullable(true)->unsigned();
            $table->string('name')->nullable(true);
            $table->timestamp('created_at')->nullable(true);
            $table->timestamp('updated_at')->nullable(true);
            $table->timestamp('deleted_at')->nullable(true);
        });
        Schema::table('cart_rows', function (Blueprint $table) {
            $table->foreign('cart_id')->references('id')->on('carts')->onDelete('cascade')->onUpdate('cascade');
        });
    }
    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        if (Schema::hasTable('cart_rows')) {
            Schema::table('cart_rows', function (Blueprint $table) {
                $table->dropForeign(['cart_id']);
            });
        }
        Schema::dropIfExists('carts');
        Schema::dropIfExists('cart_rows');
    }
}
