<?php
/* 
 * Migrations generated by: Skipper (http://www.skipper18.com)
 * Migration id: 109a8f3d-6a22-48c1-96f9-913cb035c8df
 * Migration local datetime: 2023-06-01 21:05:15.655680
 * Migration UTC datetime: 2023-06-01 19:05:15.655680
 */ 

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class SkipperMigrationsProduct2023060121051565 extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('products', function (Blueprint $table) {
            $table->bigInteger('selling_price')->nullable(true)->after('cache_price_campaign');
        });
        /* Reordering of existing columns is not supported by Laravel Eloquent.
        Schema::table('products', function (Blueprint $table) {
            $table->moveColumnAfter('bb_sku', 'selling_price');
        });
        */
        
        /* But you can create your own migrations with following SQL query based on your target SQL engine.
        DB::transaction(function () {
            DB::statement('ALTER TABLE `products` MODIFY `bb_sku` [COLUMN_DEF] AFTER `selling_price`');
        });
        */
    }
    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        /* Reordering of existing columns is not supported by Laravel Eloquent.
        Schema::table('products', function (Blueprint $table) {
            $table->moveColumnAfter('bb_sku', 'cache_price_campaign');
        });
        */
        
        /* But you can create your own migrations with following SQL query based on your target SQL engine.
        DB::transaction(function () {
            DB::statement('ALTER TABLE `products` MODIFY `bb_sku` [COLUMN_DEF] AFTER `cache_price_campaign`');
        });
        */
        Schema::table('products', function (Blueprint $table) {
            $table->dropColumn('selling_price');
        });
    }
}
