<?php
/* 
 * Migrations generated by: Skipper (http://www.skipper18.com)
 * Migration id: 109a8f3d-6a22-48c1-96f9-913cb035c8df
 * Migration local datetime: 2023-06-01 21:05:15.655680
 * Migration UTC datetime: 2023-06-01 19:05:15.655680
 */ 

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class SkipperMigrationsPricefile2023060121051565 extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('bbproducts', function (Blueprint $table) {
            $table->string('manufacturer')->nullable(true)->after('sku');
        });
    }
    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('bbproducts', function (Blueprint $table) {
            $table->dropColumn('manufacturer');
        });
    }
}
