<?php
/* 
 * Migrations generated by: Skipper (http://www.skipper18.com)
 * Migration id: 52d87de8-787d-4dbc-ac5a-4bc98d61d340
 * Migration local datetime: 2023-05-26 22:40:19.386064
 * Migration UTC datetime: 2023-05-26 20:40:19.386064
 */ 

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class SkipperMigrations2023052622401938 extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('products', function (Blueprint $table) {
            $table->json('meta')->nullable(true)->after('unit');
        });
    }
    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('products', function (Blueprint $table) {
            $table->dropColumn('meta');
        });
    }
}
