<?php
/* 
 * Migrations generated by: Skipper (http://www.skipper18.com)
 * Migration id: 57d9da42-185b-43e9-9026-6607b38716c9
 * Migration local datetime: 2023-05-15 21:26:22.707312
 * Migration UTC datetime: 2023-05-15 19:26:22.707312
 */ 

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class SkipperMigrations2023051521262270 extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tickets', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('email')->nullable(true);
            $table->text('question')->nullable(true);
            $table->text('answer')->nullable(true);
            $table->bigInteger('answer_by')->nullable(true)->unsigned();
            $table->timestamp('answer_at')->nullable(true);
            $table->timestamp('created_at')->nullable(true);
            $table->timestamp('updated_at')->nullable(true);
            $table->timestamp('deleted_at')->nullable(true);
        });
        Schema::table('tickets', function (Blueprint $table) {
            $table->foreign('answer_by')->references('id')->on('users')->onDelete('set null')->onUpdate('cascade');
        });
    }
    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        if (Schema::hasTable('tickets')) {
            Schema::table('tickets', function (Blueprint $table) {
                $table->dropForeign(['answer_by']);
            });
        }
        Schema::dropIfExists('tickets');
    }
}
