<?php
/* 
 * Migrations generated by: Skipper (http://www.skipper18.com)
 * Migration id: 3997d523-5b70-49e3-8d76-ce96f5a7b556
 * Migration local datetime: 2023-05-16 22:42:29.515882
 * Migration UTC datetime: 2023-05-16 20:42:29.515882
 */ 

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class SkipperMigrations2023051622422951 extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('products', function (Blueprint $table) {
            $table->bigInteger('cache_price_price')->nullable(true)->after('bb_id');
        });
        Schema::table('products', function (Blueprint $table) {
            $table->bigInteger('cache_price_campaign_price')->nullable(true)->after('cache_price_price');
        });
        Schema::table('products', function (Blueprint $table) {
            $table->boolean('cache_price_realisation')->nullable(true)->after('cache_price_campaign_price');
        });
        Schema::table('products', function (Blueprint $table) {
            $table->boolean('cache_price_campaign')->nullable(true)->after('cache_price_realisation');
        });
        Schema::table('selling_price', function (Blueprint $table) {
            $table->index(['deleted_at'], 'SellingPriceIndexDeletedAt');
        });
    }
    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('selling_price', function (Blueprint $table) {
            $table->dropIndex('SellingPriceIndexDeletedAt');
        });
        Schema::table('products', function (Blueprint $table) {
            $table->dropColumn('cache_price_campaign');
        });
        Schema::table('products', function (Blueprint $table) {
            $table->dropColumn('cache_price_realisation');
        });
        Schema::table('products', function (Blueprint $table) {
            $table->dropColumn('cache_price_campaign_price');
        });
        Schema::table('products', function (Blueprint $table) {
            $table->dropColumn('cache_price_price');
        });
    }
}
