<?php
/* 
 * Migrations generated by: Skipper (http://www.skipper18.com)
 * Migration id: 465a06a9-aef9-4d1c-995c-c416ad5166db
 * Migration local datetime: 2023-05-21 00:02:27.063413
 * Migration UTC datetime: 2023-05-20 22:02:27.063413
 */ 

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class SkipperMigrations2023052100022706 extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('selling_price', function (Blueprint $table) {
            $table->bigInteger('discounted_price')->after('price');
        });
        Schema::table('products', function (Blueprint $table) {
            $table->bigInteger('cache_price_discounted_price')->nullable(true)->after('cache_price_campaign_price');
        });
        Schema::table('products', function (Blueprint $table) {
            $table->timestamp('discounted_from')->nullable(true)->after('image');
        });
        Schema::table('products', function (Blueprint $table) {
            $table->timestamp('discounted_to')->nullable(true)->after('discounted_from');
        });
        Schema::table('products', function (Blueprint $table) {
            $table->tinyInteger('discounted_percentage')->nullable(true)->default(0)->after('discounted_to');
        });
    }
    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('products', function (Blueprint $table) {
            $table->dropColumn('discounted_percentage');
        });
        Schema::table('products', function (Blueprint $table) {
            $table->dropColumn('discounted_to');
        });
        Schema::table('products', function (Blueprint $table) {
            $table->dropColumn('discounted_from');
        });
        Schema::table('products', function (Blueprint $table) {
            $table->dropColumn('cache_price_discounted_price');
        });
        Schema::table('selling_price', function (Blueprint $table) {
            $table->dropColumn('discounted_price');
        });
    }
}
