<?php
/* 
 * Migrations generated by: Skipper (http://www.skipper18.com)
 * Migration id: e5d0f335-9e01-4592-b7aa-3a5cae12117b
 * Migration local datetime: 2023-04-30 20:47:49.177812
 * Migration UTC datetime: 2023-04-30 18:47:49.177812
 */ 

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class SkipperMigrations01Pricefile2023043020474917 extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('files', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('name')->nullable(true);
            $table->timestamp('file_timestamp')->nullable(true);
            $table->bigInteger('size')->nullable(true);
            $table->string('hash_md5')->nullable(true);
            $table->string('hash_sha1')->nullable(true);
            $table->boolean('api')->default(False);
            $table->timestamp('start_at')->nullable(true);
            $table->timestamp('done_at')->nullable(true);
            $table->timestamp('created_at')->nullable(true);
            $table->timestamp('updated_at')->nullable(true);
            $table->timestamp('deleted_at')->nullable(true);
            $table->index(['created_at'], 'FilesIndex');
        });
        Schema::create('despecs', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->bigInteger('file_id')->nullable(true)->unsigned();
            $table->string('item_id')->nullable(true);
            $table->integer('qty')->nullable(true);
            $table->string('item_oem')->nullable(true);
            $table->string('item_ean')->nullable(true);
            $table->string('item')->nullable(true);
            $table->string('item_txt')->nullable(true);
            $table->text('item_web_desc')->nullable(true);
            $table->string('unit')->nullable(true);
            $table->integer('stock_actual')->nullable(true);
            $table->date('expected_date')->nullable(true);
            $table->bigInteger('price')->nullable(true);
            $table->bigInteger('price_tax_and_fees')->nullable(true);
            $table->string('currency')->nullable(true);
            $table->bigInteger('vat_tax')->nullable(true);
            $table->string('item_type')->nullable(true);
            $table->string('brand')->nullable(true);
            $table->bigInteger('weight')->nullable(true);
            $table->bigInteger('volume')->nullable(true);
            $table->bigInteger('height')->nullable(true);
            $table->bigInteger('width')->nullable(true);
            $table->bigInteger('depth')->nullable(true);
            $table->bigInteger('add_fees_tax')->nullable(true);
            $table->string('cust_item_id')->nullable(true);
            $table->string('create_date_time')->nullable(true);
            $table->string('stat_code')->nullable(true);
            $table->string('orig_country')->nullable(true);
            $table->bigInteger('min_q')->nullable(true);
            $table->integer('multiples')->nullable(true);
            $table->integer('colli')->nullable(true);
            $table->string('brand_txt')->nullable(true);
            $table->string('item_type_txt')->nullable(true);
            $table->string('non_stock_item_txt')->nullable(true);
            $table->string('bid_id')->nullable(true);
            $table->timestamp('created_at')->nullable(true);
            $table->timestamp('updated_at')->nullable(true);
            $table->timestamp('deleted_at')->nullable(true);
            $table->index(['file_id'], 'DespecIndexFileId');
            $table->index(['file_id','item_id'], 'DespecIndexComp');
        });
        Schema::create('bbproducts', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->bigInteger('id_api')->nullable(true);
            $table->string('sku')->nullable(true);
            $table->string('ean13')->nullable(true);
            $table->decimal('weight', 10, 2)->nullable(true);
            $table->decimal('height', 10, 2)->nullable(true);
            $table->decimal('width', 10, 2)->nullable(true);
            $table->decimal('depth', 10, 2)->nullable(true);
            $table->dateTime('dateUpd')->nullable(true);
            $table->bigInteger('category')->nullable(true);
            $table->dateTime('dateUpdDescription')->nullable(true);
            $table->dateTime('dateUpdImages')->nullable(true);
            $table->dateTime('dateUpdStock')->nullable(true);
            $table->decimal('wholesalePrice', 10, 2)->nullable(true);
            $table->decimal('retailPrice', 10, 2)->nullable(true);
            $table->dateTime('dateAdd')->nullable(true);
            $table->string('video')->nullable(true);
            $table->boolean('active')->nullable(true);
            $table->boolean('attributes')->nullable(true);
            $table->boolean('categories')->nullable(true);
            $table->boolean('images')->nullable(true);
            $table->integer('taxRate')->nullable(true);
            $table->integer('taxId')->nullable(true);
            $table->decimal('inShopsPrice', 10, 2)->nullable(true);
            $table->string('condition')->nullable(true);
            $table->string('logisticClass')->nullable(true);
            $table->boolean('tags')->nullable(true);
            $table->string('intrastat')->nullable(true);
            $table->index(['id_api'], 'BBProductIndexIdApi');
            $table->index(['sku'], 'BBProductIndexSku');
            $table->index(['ean13'], 'BBProductIndexEan13');
        });
        Schema::create('bbmanufacturer', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->bigInteger('id_api')->nullable(true);
            $table->string('name')->nullable(true);
            $table->string('url_image')->nullable(true);
            $table->bigInteger('reference')->nullable(true);
            $table->boolean('active')->nullable(true)->default(false);
            $table->timestamp('created_at')->nullable(true);
            $table->timestamp('updated_at')->nullable(true);
            $table->timestamp('deleted_at')->nullable(true);
            $table->index(['id_api'], 'BBManufacturerIndexIdApi');
            $table->index(['active'], 'BBManufacturerIndexActive');
            $table->index(['created_at','updated_at','deleted_at'], 'BBManufacturerIndexTimes');
        });
        Schema::create('bbcategories', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->bigInteger('id_api')->nullable(true);
            $table->bigInteger('parent_id')->nullable(true);
            $table->string('name')->nullable(true);
            $table->string('urls')->nullable(true);
            $table->string('image_urls')->nullable(true);
            $table->dateTime('date_add')->nullable(true);
            $table->dateTime('date_upd')->nullable(true);
            $table->timestamp('created_at')->nullable(true);
            $table->timestamp('updated_at')->nullable(true);
            $table->timestamp('deleted_at')->nullable(true);
            $table->index(['id_api'], 'BBCategoryIdApi');
            $table->index(['parent_id'], 'BBCategoryParintId');
            $table->index(['deleted_at','updated_at','created_at'], 'BBCategoryTimes');
        });
        Schema::create('bbimages', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->bigInteger('id_api')->nullable(true);
            $table->bigInteger('image_id')->nullable(true);
            $table->string('url')->nullable(true);
            $table->boolean('cover')->nullable(true)->default(false);
            $table->boolean('logo')->nullable(true)->default(false);
            $table->boolean('whiteBackground')->nullable(true)->default(false);
            $table->string('file')->nullable(true);
            $table->timestamp('created_at')->nullable(true);
            $table->timestamp('updated_at')->nullable(true);
            $table->timestamp('deleted_at')->nullable(true);
            $table->index(['id_api'], 'BBImageIndexIdAPI');
            $table->index(['logo'], 'BBImageIndexLogo');
            $table->index(['cover'], 'BBImageIndexCover');
            $table->index(['created_at','deleted_at','updated_at'], 'BBImageIndexIdTimes');
        });
        Schema::create('bbstocks', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->bigInteger('id_api')->nullable(true);
            $table->string('sku')->nullable(true);
            $table->bigInteger('stock_quantity')->nullable(true);
            $table->bigInteger('stock_min_handling_days')->nullable(true);
            $table->bigInteger('stock_max_handling_days')->nullable(true);
            $table->bigInteger('stock_warehouse')->nullable(true);
            $table->timestamp('updated_at')->nullable(true);
            $table->timestamp('created_at')->nullable(true);
            $table->index(['id_api'], 'BBStockIndexIdApi');
            $table->index(['sku'], 'BBStockIndexSku');
            $table->index(['created_at','updated_at'], 'BBStockIndexTimes');
        });
        Schema::create('bbshippings', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('reference')->nullable(true);
            $table->double('cost', 10, 2)->nullable(true);
            $table->bigInteger('carrierId')->nullable(true);
            $table->string('carrierName')->nullable(true);
            $table->timestamp('created_at')->nullable(true);
            $table->timestamp('updated_at')->nullable(true);
            $table->index(['reference'], 'BBShippingIndexReference');
            $table->index(['carrierName'], 'BBShippingIndexCarrierName');
            $table->index(['updated_at','created_at'], 'BBShippingIndexTimes');
        });
        Schema::create('bbinformation', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->bigInteger('id_api')->nullable(true);
            $table->string('sku')->nullable(true);
            $table->string('name')->nullable(true);
            $table->text('description')->nullable(true);
            $table->string('url')->nullable(true);
            $table->dateTime('dateUpdDescription')->nullable(true);
            $table->text('shortDescription')->nullable(true);
            $table->text('descriptionRetailer')->nullable(true);
            $table->text('translation')->nullable(true);
            $table->text('metaKeywords')->nullable(true);
            $table->text('manufacturer')->nullable(true);
            $table->timestamp('created_at')->nullable(true);
            $table->timestamp('updated_at')->nullable(true);
            $table->index(['id_api'], 'BBInformationIndexIdApi');
            $table->index(['sku'], 'BBInformationIndexSku');
            $table->index(['dateUpdDescription'], 'BBInformationIndexUpdateDes');
            $table->index(['created_at','updated_at'], 'BBInformationIndexTimes');
        });
        Schema::create('bbcategories_subscribe', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('categorie')->nullable(true);
            $table->boolean('follow')->nullable(true)->default(true);
            $table->boolean('block')->nullable(true)->default(false);
            $table->boolean('recursive')->nullable(true)->default(false);
            $table->timestamp('created_at')->nullable(true);
            $table->timestamp('updated_at')->nullable(true);
            $table->index(['categorie'], 'BBCategoriesSubscribeIndexCategorie');
            $table->index(['follow'], 'BBCategoriesSubscribeIndexFollow');
            $table->index(['updated_at','created_at'], 'BBCategoriesSubscribeIndexTimes');
        });
        Schema::create('bbproducts_taxonomies', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->bigInteger('taxonomy')->nullable(true)->unsigned();
            $table->bigInteger('product')->nullable(true)->unsigned();
            $table->index(['product'], 'BBProductsTaxonomiesIndexProduct');
            $table->index(['taxonomy'], 'BBProductsTaxonomiesIndexTaxonomy');
        });
        Schema::create('bbskumanufacturer', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->bigInteger('brand_id')->nullable(true);
            $table->string('sku')->nullable(true);
            $table->timestamp('created_at')->nullable(true);
            $table->timestamp('updated_at')->nullable(true);
            $table->timestamp('deleted_at')->nullable(true);
            $table->index(['sku'], 'BBSkuManufacturerIndexSku');
        });
        Schema::table('despecs', function (Blueprint $table) {
            $table->foreign('file_id')->references('id')->on('files')->onDelete('cascade')->onUpdate('cascade');
        });
    }
    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        if (Schema::hasTable('despecs')) {
            Schema::table('despecs', function (Blueprint $table) {
                $table->dropForeign(['file_id']);
            });
        }
        Schema::dropIfExists('bbskumanufacturer');
        Schema::dropIfExists('bbproducts_taxonomies');
        Schema::dropIfExists('bbcategories_subscribe');
        Schema::dropIfExists('bbinformation');
        Schema::dropIfExists('bbshippings');
        Schema::dropIfExists('bbstocks');
        Schema::dropIfExists('bbimages');
        Schema::dropIfExists('bbcategories');
        Schema::dropIfExists('bbmanufacturer');
        Schema::dropIfExists('bbproducts');
        Schema::dropIfExists('despecs');
        Schema::dropIfExists('files');
    }
}
