<?php
/* 
 * Migrations generated by: Skipper (http://www.skipper18.com)
 * Migration id: e5d0f335-9e01-4592-b7aa-3a5cae12117b-02
 * Migration local datetime: 2023-04-30 20:47:49.177812
 * Migration UTC datetime: 2023-04-30 18:47:49.177812
 */ 

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class SkipperMigrations02Order2023043020474917 extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('orders', function (Blueprint $table) {
            $table->foreign('customer_id')->references('id')->on('customers')->onDelete('set null')->onUpdate('cascade');
        });
        Schema::table('orders', function (Blueprint $table) {
            $table->foreign('user_id')->references('id')->on('users')->onDelete('set null')->onUpdate('cascade');
        });
        Schema::table('purchase_orders', function (Blueprint $table) {
            $table->foreign('supplier_id')->references('id')->on('suppliers')->onDelete('restrict')->onUpdate('cascade');
        });
        Schema::table('order_rows', function (Blueprint $table) {
            $table->foreign('supplier_id')->references('id')->on('suppliers')->onDelete('restrict')->onUpdate('cascade');
        });
        Schema::table('order_rows', function (Blueprint $table) {
            $table->foreign('partner_id')->references('id')->on('partners')->onDelete('set null')->onUpdate('cascade');
        });
        Schema::table('order_rows', function (Blueprint $table) {
            $table->foreign('discount_code_id')->references('id')->on('discount_codes')->onDelete('set null')->onUpdate('restrict');
        });
    }
    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        if (Schema::hasTable('order_rows')) {
            Schema::table('order_rows', function (Blueprint $table) {
                $table->dropForeign(['discount_code_id']);
            });
        }
        if (Schema::hasTable('order_rows')) {
            Schema::table('order_rows', function (Blueprint $table) {
                $table->dropForeign(['partner_id']);
            });
        }
        if (Schema::hasTable('order_rows')) {
            Schema::table('order_rows', function (Blueprint $table) {
                $table->dropForeign(['supplier_id']);
            });
        }
        if (Schema::hasTable('purchase_orders')) {
            Schema::table('purchase_orders', function (Blueprint $table) {
                $table->dropForeign(['supplier_id']);
            });
        }
        if (Schema::hasTable('orders')) {
            Schema::table('orders', function (Blueprint $table) {
                $table->dropForeign(['user_id']);
            });
        }
        if (Schema::hasTable('orders')) {
            Schema::table('orders', function (Blueprint $table) {
                $table->dropForeign(['customer_id']);
            });
        }
    }
}
