<?php
/* 
 * Migrations generated by: Skipper (http://www.skipper18.com)
 * Migration id: e5d0f335-9e01-4592-b7aa-3a5cae12117b-01
 * Migration local datetime: 2023-04-30 20:47:49.177812
 * Migration UTC datetime: 2023-04-30 18:47:49.177812
 */ 

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class SkipperMigrations01Partner2023043020474917 extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('partners', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->bigInteger('user_id')->nullable(true)->default(null)->unsigned();
            $table->boolean('active')->default(0);
            $table->enum('partner_type', ['Private','Company']);
            $table->enum('partner_level', ['Bronze Partner','Iron Partner','Silver Partner','Gold Partner','Platinum Partner'])->default('Bronze Partner');
            $table->string('image', 255)->nullable(true);
            $table->string('first_name', 255)->nullable(true);
            $table->string('last_name', 255)->nullable(true);
            $table->string('ssn', 255)->nullable(true);
            $table->string('email', 255)->nullable(true);
            $table->string('phone', 255)->nullable(true);
            $table->string('address', 255)->nullable(true);
            $table->string('postal_code', 255)->nullable(true);
            $table->string('city', 255)->nullable(true);
            $table->string('vat_number', 255)->nullable(true);
            $table->integer('number_of_payouts')->default(0);
            $table->string('email_validate_code', 255)->nullable(true);
            $table->timestamp('email_validated_at')->nullable(true);
            $table->timestamp('phone_validated_at')->nullable(true);
            $table->string('twitch_url', 255)->nullable(true);
            $table->string('youtube_url', 255)->nullable(true);
            $table->string('instagram_url', 255)->nullable(true);
            $table->string('facebook_url', 255)->nullable(true);
            $table->timestamp('created_at')->nullable(true);
            $table->timestamp('updated_at')->nullable(true);
            $table->timestamp('deleted_at')->nullable(true);
        });
        Schema::create('partner_subscribers', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('email', 255);
            $table->timestamp('created_at')->nullable(true);
            $table->timestamp('updated_at')->nullable(true);
            $table->timestamp('deleted_at')->nullable(true);
        });
        Schema::create('discount_codes', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->bigInteger('partner_id')->nullable(true)->unsigned();
            $table->string('partner_name')->nullable(true);
            $table->string('code')->nullable(true);
            $table->timestamp('created_at')->nullable(true);
            $table->timestamp('updated_at')->nullable(true);
            $table->timestamp('deleted_at')->nullable(true);
            $table->unique(['code','deleted_at'], 'partner_code_unique');
            $table->index(['code'], 'partner_code_index');
            $table->index(['partner_id'], 'partner_code_index_partnter');
        });
        Schema::create('ledger', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->bigInteger('partner_id')->nullable(true)->unsigned();
            $table->string('number')->nullable(true);
            $table->bigInteger('snapshot_sum');
            $table->bigInteger('snapshot_id');
            $table->timestamp('created_at')->nullable(true);
            $table->timestamp('updated_at')->nullable(true);
            $table->index(['partner_id'], 'LedgerIndexParternId');
        });
        Schema::create('transactions', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->bigInteger('ledger_id')->unsigned();
            $table->bigInteger('order_row_id')->nullable(true)->unsigned();
            $table->bigInteger('user_id')->nullable(true)->unsigned();
            $table->bigInteger('amount');
            $table->timestamp('active_at');
            $table->string('description');
            $table->json('orders')->nullable(true);
            $table->timestamp('created_at');
            $table->timestamp('updated_at');
            $table->index(['ledger_id'], 'TransactionsIndexLedgerId');
            $table->index(['active_at'], 'TransactionsIndexActiveAt');
            $table->index(['ledger_id','active_at'], 'TransactionsIndexActiveAtLedgerId');
        });
        Schema::table('discount_codes', function (Blueprint $table) {
            $table->foreign('partner_id')->references('id')->on('partners')->onDelete('set null')->onUpdate('cascade');
        });
        Schema::table('ledger', function (Blueprint $table) {
            $table->foreign('partner_id')->references('id')->on('partners')->onDelete('restrict')->onUpdate('cascade');
        });
        Schema::table('transactions', function (Blueprint $table) {
            $table->foreign('ledger_id')->references('id')->on('ledger')->onDelete('restrict')->onUpdate('cascade');
        });
    }
    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        if (Schema::hasTable('transactions')) {
            Schema::table('transactions', function (Blueprint $table) {
                $table->dropForeign(['ledger_id']);
            });
        }
        if (Schema::hasTable('ledger')) {
            Schema::table('ledger', function (Blueprint $table) {
                $table->dropForeign(['partner_id']);
            });
        }
        if (Schema::hasTable('discount_codes')) {
            Schema::table('discount_codes', function (Blueprint $table) {
                $table->dropForeign(['partner_id']);
            });
        }
        Schema::dropIfExists('transactions');
        Schema::dropIfExists('ledger');
        Schema::dropIfExists('discount_codes');
        Schema::dropIfExists('partner_subscribers');
        Schema::dropIfExists('partners');
    }
}
