<?php
/* 
 * Migrations generated by: Skipper (http://www.skipper18.com)
 * Migration id: d8324c25-99c5-4548-8014-6221e11ac23d
 * Migration local datetime: 2023-05-17 18:29:08.670545
 * Migration UTC datetime: 2023-05-17 16:29:08.670545
 */ 

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class SkipperMigrations2023051718290867 extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('selling_price', function (Blueprint $table) {
            $table->index(['created_at'], 'SellingPriceIndexCreatedAt');
        });
    }
    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('selling_price', function (Blueprint $table) {
            $table->dropIndex('SellingPriceIndexCreatedAt');
        });
    }
}
