<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\Profile\AbstractModels;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
* Class AbstractAddress
* @package App\Models\Profile\AbstractModels
*
* @property bigInteger $id
* @property bigInteger $customer_id
* @property boolean $billing
* @property boolean $shipping
* @property string $firstname
* @property string $lastname
* @property string $address
* @property string $postal_code
* @property string $city
* @property string $state
* @property string $country
* @property string $email
* @property string $phone
* @property \Carbon\Carbon $created_at
* @property \Carbon\Carbon $updated_at
* @property \Carbon\Carbon $deleted_at
* @property \App\Models\Profile\Customer|null $customer
*/ 
abstract class AbstractAddress extends Model
{
    use SoftDeletes;
    
    /**  
     * The model's default values for attributes.
     * 
     * @var array
     */
    protected $attributes = [
        'billing' => true,
        'shipping' => true,
        'country' => 'SE'
    ];
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'customer_id' => 'integer',
        'billing' => 'boolean',
        'shipping' => 'boolean',
        'firstname' => 'string',
        'lastname' => 'string',
        'address' => 'string',
        'postal_code' => 'string',
        'city' => 'string',
        'state' => 'string',
        'country' => 'string',
        'email' => 'string',
        'phone' => 'string',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
        'deleted_at' => 'datetime'
    ];
    
    /**  
     * The attributes that are mass assignable.
     * 
     * @var array
     */
    protected $fillable = [
        'customer_id',
        'firstname',
        'lastname',
        'address',
        'postal_code',
        'city',
        'state',
        'country',
        'email'
    ];
    
    public function customer()
    {
        return $this->belongsTo('\App\Models\Profile\Customer', 'customer_id', 'id');
    }
}
