<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\Profile\AbstractModels;

use Illuminate\Database\Eloquent\Model;

/**
* Class AbstractCustomer
* @package App\Models\Profile\AbstractModels
*
* @property bigInteger $id
* @property bigInteger $user_id
* @property string $ssn
* @property string $firstname
* @property string $lastname
* @property string $phone
* @property string $email
* @property \Carbon\Carbon $created_at
* @property \Carbon\Carbon $updated_at
* @property \App\Models\User|null $user
* @property \Illuminate\Database\Eloquent\Collection $addresses
* @property \Illuminate\Database\Eloquent\Collection $orders
*/ 
abstract class AbstractCustomer extends Model
{
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'user_id' => 'integer',
        'ssn' => 'string',
        'firstname' => 'string',
        'lastname' => 'string',
        'phone' => 'string',
        'email' => 'string',
        'created_at' => 'datetime',
        'updated_at' => 'datetime'
    ];
    
    /**  
     * The attributes that are mass assignable.
     * 
     * @var array
     */
    protected $fillable = [
        'user_id',
        'ssn',
        'firstname',
        'lastname',
        'phone',
        'email'
    ];
    
    public function user()
    {
        return $this->belongsTo('\App\Models\User', 'user_id', 'id');
    }
    
    public function addresses()
    {
        return $this->hasMany('\App\Models\Profile\Address', 'customer_id', 'id');
    }
    
    public function orders()
    {
        return $this->hasMany('\App\Models\Order\Order', 'customer_id', 'id');
    }
}
